#' @include RP.R
#' @include RV.R
#' @include sample_ep.R
NULL

.check_GenCouponPartition <- function(object) {
  errors = character()
  if (!is_scalar(object@m) && !is.ShiftedNegBinomRV(object@m)) {
    errors <- c(errors, "m must be a scalar or a ShiftedNegBinomRV")
  }
  if (!is_scalar(object@kappa) & !is.GammaRV(object@kappa)) {
    errors <- c(errors, "kappa must be a scalar or a GammaRV")
  }
  if (is_numeric_scalar(object@m)) {
    if (object@m <= 0)
      errors <- c(errors, "m must be positive")
    if (as.integer(object@m) != object@m) 
      errors <- c(errors, "m must be an integer")
  }
  if (is_numeric_scalar(object@kappa)) {
    if (object@kappa <= 0) {
      errors <- c(errors, "kappa must be strictly positive")
    }  
  }
  if (length(errors)==0) TRUE else errors
}

setClass("GeneralizedCouponRP", 
         slots = c(m="ANY", kappa="ANY"), 
         validity=.check_GenCouponPartition, contains = "RP")

#' Generalized Coupon Random Partition
#' 
#' @description
#' Represents a generalized coupon random partition.
#' 
#' @details 
#' Generalized coupon random partitions are a subset of Ewens-Pitman random 
#' partitions for which \eqn{\kappa = - \sigma > 0}{κ = -σ > 0} and 
#' \eqn{\alpha = m \kappa}{ɑ = m κ} for some natural number \eqn{m}. 
#' These partitions can be generated by drawing coupons with replacement from 
#' a finite population of size \eqn{m}, where the mixing proportions are 
#' drawn from a symmetric Dirichlet distribution with concentration parameter
#' \eqn{\kappa}{κ}. The coupon-collector's partition is obtained in the limit 
#' \eqn{\kappa \to \infty}{κ -> Inf}.
#' 
#' @param m Number of coupons. Must be a strictly positive integer 
#'   or a [`ShiftedNegBinomRV`] object.
#' @param kappa Concentration parameter. Must be strictly a positive real or 
#'   a [`GammaRV`] object.
#' @return The constructor `GeneralizedCouponRP` returns a 
#'   `GeneralizedCouponRP` object which is a subclass of [`RP-class`].
#' 
#' @seealso 
#' Other random partitions defined in this package include [`PitmanYorRP`] and 
#' [`EwensRP`].
#' 
#' @export
GeneralizedCouponRP <- function(m, kappa) {
  new("GeneralizedCouponRP", m=m, kappa=kappa)
}

setMethod("format", "GeneralizedCouponRP", function(x, ...) {
  m <- format(x@m, ...)
  kappa <- format(x@kappa, ...)
  paste0("GeneralizedCouponRP(m=", m, ", kappa=", kappa, ")")
})

setMethod("show", "GeneralizedCouponRP", function(object) {
  writeLines(format(object))
  invisible(object)
})

#' @param x An \R object.
#' @return `is.GeneralizedCouponRP` returns TRUE if the argument is a 
#'   `GeneralizedCouponRP` object and FALSE otherwise.
#' 
#' @noRd
#' @keywords internal
is.GeneralizedCouponRP <- function(x) inherits(x, "GeneralizedCouponRP")

#' @describeIn rrp Specialization for [`GeneralizedCouponRV`]
#' @export
setMethod("rrp", signature(rp = "GeneralizedCouponRP"), 
          function(rp, n, ...) {
            m <- if (is.RV(rp@m)) rrv(rp@m) else rp@m
            kappa <- if (is.RV(rp@kappa)) rrv(rp@kappa) else rp@kappa
            alpha <- m * kappa
            sigma <- -kappa
            sample_ewens_pitman(n, alpha, sigma)
          })