#' @include RP.R
#' @include RV.R
#' @include sample_ep.R
NULL

.check_PitmanYorPartition <- function(object) {
  errors = character()
  if (!is_scalar(object@alpha) & !is.GammaRV(object@alpha)) {
    errors <- c(errors, "alpha must be a scalar or a GammaRV")
  }
  if (!is_scalar(object@d) & !is.BetaRV(object@d)) {
    errors <- c(errors, "beta must be a scalar or a BetaRV")
  }
  if (is_numeric_scalar(object@alpha)) {
    if (is_numeric_scalar(object@d)) {
      if (object@alpha <= -object@d) {
        errors <- c(errors, "alpha must be > -d")
      }
    } else {
      if (object@alpha <= 0) {
        errors <- c(errors, "alpha must be > 0")
      }  
    }
    if (!is.finite(object@alpha)) {
      errors <- c(errors, "alpha must be finite")
    }
  }
  if (is_numeric_scalar(object@d)) {
    if (object@d < 0. | object@d >= 1.) {
      errors <- c(errors, "d must be on the interval [0, 1)")
    }  
  }
  if (length(errors)==0) TRUE else errors
}

setClass("PitmanYorRP", 
         slots = c(alpha="ANY", d="ANY"), 
         validity=.check_PitmanYorPartition, contains = "RP")

#' Pitman-Yor Random Partition
#' 
#' @description
#' Represents a Pitman-Yor random partition.
#' 
#' @details 
#' Pitman-Yor random partitions are a subset of Ewens-Pitman random partitions 
#' for which \eqn{0 \leq \sigma \leq 1}{0 <= σ <= 1} and 
#' \eqn{\alpha > - \sigma}{ɑ > -σ}. These partitions can be generated by 
#' sampling with replacement from an infinite population, where the mixing 
#' proportions are drawn from a two-parameter Poisson-Dirichlet distribution.
#'
#' @param alpha Concentration parameter that satisfies \eqn{alpha > -d} 
#'   or a [`GammaRV`].
#' @param d Discount parameter that satisfies \eqn{0 \leq d < 1}{0 <= d < 1} 
#'   or a [`BetaRV`].
#' @return The constructor `PitmanYorRP` returns a `PitmanYorRP` 
#'   object which is a subclass of [`RP-class`].
#'  
#' @seealso 
#' Other random partitions defined in this package include [`EwensRP`] and 
#' [`GeneralizedCouponRP`].
#' 
#' @export
PitmanYorRP <- function(alpha, d) {
  new("PitmanYorRP", alpha=alpha, d=d)
}

#' @param x An \R object.
#' @return `is.PitmanYorRP` returns TRUE if the argument is a 
#' `PitmanYorRP` object and FALSE otherwise.
#' 
#' @noRd
#' @keywords internal
is.PitmanYorRP <- function(x) inherits(x, "PitmanYorRP")

setMethod("format", "PitmanYorRP", function(x, ...) {
  alpha <- format(x@alpha, ...)
  d <- format(x@d, ...)
  paste0("PitmanYorRP(alpha=", alpha, ", d=", d, ")")
})

setMethod("show", "PitmanYorRP", function(object) {
  writeLines(format(object))
  invisible(object)
})

#' Ewens Random Partition
#' 
#' @description
#' Represents a Ewens random partition.
#' 
#' @details
#' This is a special case of the Pitman-Yor partition (see [`PitmanYorRP`]) 
#' for which the discount parameter \eqn{d = 0}. It exhibits distinct 
#' asymptotic behavior: the number of clusters grows logarithmically in 
#' the number of data points.
#' 
#' @param alpha Positive concentration parameter or a [`GammaRV`].
#' @return The constructor `EwensRP` returns a `PitmanYorRP` 
#'   object which is a subclass of [`RP-class`].
#' 
#' @seealso 
#' Other random partitions defined in this package include [`PitmanYorRP`] and 
#' [`GeneralizedCouponRP`].
#' 
#' @export
EwensRP <- function(alpha) {
  new("PitmanYorRP", alpha=alpha, d=0.)
}

#' @param x An \R object.
#' @return `is.EwensRP` returns TRUE if the argument is a 
#'   `EwensRP` object and FALSE otherwise.
#' 
#' @noRd
#' @keywords internal
is.EwensRP <- function(x) {
  return(inherits(x, "PitmanYorRP") && (x@d == 0.))
}

#' @describeIn rrp Specialization for [`PitmanYorRP`]
#' @export
setMethod("rrp", signature(rp = "PitmanYorRP"), 
          function(rp, n, ...) {
            sigma <- if (is.RV(rp@d)) rrv(rp@d) else rp@d
            alpha <- if (is.RV(rp@alpha)) rrv(rp@alpha) else rp@alpha
            sample_ewens_pitman(n, alpha, sigma)
          })